name: pull_request
on: 
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.*
    - name: Install dependencies
      run: dotnet restore
    - uses: shogo82148/actions-setup-mysql@v1
      with:
          mysql-version: '8.0'
    - name: Build and test
      run: dotnet test --configuration Release --no-restore --verbosity normal
